### ISSUE TITLE
Team: Overlay does not scale when main menu is open

### ISSUE THREAD

**Issue by patrickkraaij** [codezilla-nl/codezilla-website#83]
When opening the main menu at 'Team' page and when you click on a team member, the overlay does not have a ```perspective``` CSS property.
![menu-open-teamlid-overlay](https://user-images.githubusercontent.com/618788/26946758-aa417a92-4c90-11e7-9e40-0822841df5ff.gif)

**Comment by jellekralt** [comment]
I don't know if its a great idea to add perspective to the team overlay, because that would mean it would have to overlay the entire body (which probably would look a bit weird), instead of just the viewport. Maybe it would be better to just try to fix the overlay over the navigation, so it will still take the entire viewport?

**Comment by patrickkraaij** [comment]
> Maybe it would be better to just try to fix the overlay over the navigation, so it will still take the entire viewport?
This.

**Comment by basvandepol92** [comment]
When the menu page is open and the user interacts with the site the menu should close and do the action. The application already does this when switching pages (e.g. from 'visie' to 'werken-bij'). I think that the interaction with the team member page should behave the same. 
So first close the navigation and then animate in the team member frame.

**Comment by basvandepol92** [comment]
I'll create a PR for my suggestion, if you guys don't agree about this please decline the PR and I'll try to fix the overlay over the navigation to take the entire viewport.
